const carList = [];

const e211975 = new Car("E21",1975,"White", "Blue", "2 Door Coupe",18,"Manual",100.9 inches,
    "desc":"The BMW e21 was one of BMW’s first compact sedan models made by the company. The chassis code for the car, known as e21, refers to the model of the vehicle. Under this category various versions of the car were made using the e21 chassis code. The origination of this code comes from the German word for development, Entwicklung.  The car was debuted in 1975 and production ran until 1983, during these years various models of the e21 were constructed. Engines displacement, transmissions, and body styles were some of the features that were altered on the BMW e21. Initial engine specs for the BMW e21 were 4-cylinder carbureted engines, wielding 74-98 HP. Later models of the e21 included upgraded engines, including BMW’s notorious inline 6-cylinder engine. Of the 8 years of production, the e21 came in 9 different styles. The engines were upgraded from small 4-cylinder 1.5L engines, wielding 77-98hp, to six cylinder 2.3L engines, wielding 141hp. The body styles for the BMW e21 were not quite as versatile as their engines. Over the 8 years of production, the BMW e21 only came with one body style. However, a side company working with BMW offered a cabriolet (convertible) version. \n",
e211975.addEngine("Inline 4",98,1.5L);
carList.push(e211975);

const e231977 = new Car("E23",1977,"Grey", "Brown", "4 Door Sedan",20,"Automatic",110. inches,
    "desc:The BMW e23 was one of BMW’s first full sized sedan models made by the company. The chassis code for the car, known as the e23, refers to the model of the vehicle. Under this category various versions of the car were made using the e23 chassis code. The origination of this code comes from the German word for development, Entwicklung.  The car debuted in 1977 and production ran until 1986, During these years various models of the e23 were constructed. Engine displacements, transmission, and body styles were some of the features that were altered on the BMW e23. Initial models of the e23 were fitted with a carbureted system which was later phased out for a fuel injected system. Early models of the E23 boasted an inline 6-cylinder 2.5L engine, with 148hp. From here BMW designers increased the engine size and Hp output of the e23. The largest engine fitted into the e23 was an inline 6- cylinder 3.5L engine with 282hp. Body styles of the e23 remained simple, no large changes to the vehicle’s exterior were made during its 9 years of production. The only change to the vehicle’s exterior was a minor change to the front section of the car. The grille, and headlight assembly was changed for a sleeker look.  \n"
e231977.addEngine("Inline 6",148,2.5L);
carList.push(e231977);

const e241986 = new Car("E24",1986,"Black", "Black", "2 Door Coupe",16,"Manual",103.5 inches,
    "desc":"The BMW e24 was one of BMW’s most successful coupe models made by the company. The chassis code for the car, known as the e24, refers to the model of the vehicle. Under this category various versions of the car were made using the e24 chassis code. The origination of this code comes from the German word for development, Entwicklung.  The car debuted in 1976 and production ran until 1989, During these years various models of the e24 were constructed. Engine displacements, transmission, and body styles were some of the features that were altered on the BMW e24. Early models were fitted with a carbureted fuel system which was quickly phased out for a more reliable fuel injected system. Initial models of the E24 were fitted with a modest 2.8L inline 6-cylinder engine, with 183hp. Later models of the BMW E24 got a large engine upgrade, which included a 3.5L inline 6-cylinder, wielding 282hp. \nThe body styles for the BMW E24 were simple and were not drastically changed during its production. Initial vehicles were made on  the chassis of the BMW E12, later models received their own E24 chassis. Additional body style changes came in the form of the front valence for the cars, US models and European models were given unique front valences. \n"
e241986.addEngine("Inline 6",282,3.5L);
carList.push(e241986);

const e281981 = new Car("E28",1981,"Blue", "Tan", "4 Door Sedan",24,"Automatic",103.3 inches,
    "desc":"The BMW e28 was BMW’s second full sized sedan models made by the company. The chassis code for the car, known as the e28, refers to the model of the vehicle. Under this category various versions of the car were made using the e28 chassis code. The origination of this code comes from the German word for development, Entwicklung.  The car debuted in 1981 and production ran until 1988, During these years various models of the e28 were constructed. Engine displacements, transmission, and body styles were some of the features that were altered on the BMW e28. Initial models of the e28 were fitted with a carbureted system which was later phased out for a fuel injected system. Early models of the E28 boasted an 1.8L inline 4 cylinder engine with 88Hp. Later models of the E28 received a massive engine upgrade as well as overall performance changes. One of the most sought after models of the E28 was the E28 M5 which included a 3.5L inline 6 Cylinder engine with 218hp. \nNo body modifications were made for the BMW E28. With the greatest change coming in the form of the engine, other modifications were set aside. \n"
e281981.addEngine("Inline 6",218,3.5L);
carList.push(e281981);

const e301983 = new Car("E30",1983,"Grey", "Black", "2 Door Coupe",27,"Manual",101.2 inches,
    "desc":" The BMW e30 is argued to be BMW’s most successful vehicles they ever produced, selling over 2 million. The chassis code for the car, known as the e30, refers to the model of the vehicle. Under this category various versions of the car were made using the e30 chassis code. The origination of this code comes from the German word for development, Entwicklung.  The car debuted in 1982 and production ran until 1994, During these years various models of the e30 were constructed. Engine displacements, transmission, and body styles were some of the features that were altered on the BMW e30. Initial models of the e30 were not subjected to the same fault as previous vehicle models, that being the carbureted fuel system. All e30’s were fitted with fuel injection system. Initial engine sizes for the BMW were a modest 1.8L inline 4-Cylinder engine with 89hp. Later models were given the engine upgrade to a 2.7L 6-cyilinder engine with 128hp.  \nBody styles of the e30 came in quite a wide variety. With the massive success of the e30 and the simplicity of the chassis, this allowed the designers to create many different versions of the car. Two door coupe models were created, often carrying the smaller engine size usually the inline 4-cylinder. Larger 4 door sedans were also made, these mostly carried the inline 6-cylinder engine, and are more sought after by BMW collectors. Another unique model of the BWM e30 came in the form of a convertible soft top which were fitted to the two door models.  The last model created for the BMW e30 was their five door or station wagon version of the E30, this included the four door model with a extended rear cab for loading. \n"
e301983.addEngine("Inline 6",128, 2.7);
carList.push(e301983);

const e311990 = new Car("E30",1990,"Blue", "Blue", "2 Door Coupe",18,"Manual",105.7 inches,
    "desc":"The BMW e31 is the second touring or coupe car that BMW has made, the first being the notorious 6 series. With the advent of the computer age the BMW e31 was also the first BMW to be entirely designed on a computer. The BMW e31 vehicles were touring cars of the next generation and changed BMW for the better. The company was now known for creating powerful large engine coup touring cars.  The chassis code for the car, known as the e31, refers to the model of the vehicle. Under this category various versions of the car were made using the e31 chassis code. The origination of this code comes from the German word for development, Entwicklung.  The car debuted in 1990 and production ran until 1999, during these years of production few models were created. Engine displacements, and transmissions were the only features changed on the BMW e31. Initial models of the e31 were made with a massive 4.0L V8 engine with 282hp. The e31 with the largest engine was the BMW e31 850, this model was fitted with a 5.6L V8 with 375hp. \nThere were no different body styles made for the BMW e31, the car was only fitted with a card top. The BMW e31 remains a cult classic and one of the most elusive BMW models as only 7,323 were made. \n "
e311990.addEngine("V8",375, 5.6L);
carList.push(e31990);

const e341996 = new Car("E34",1996,"Red","Black", "4 Door Sedan",28,"Manual",108.7 inches,
    "desc":"The BMW e34 was BMW’s third generation full sized sedan model made by the company. The chassis code for the car, known as the e34, refers to the model of the vehicle. Under this category various versions of the car were made using the e34 chassis code. The origination of this code comes from the German word for development, Entwicklung.  The car debuted in 1987 and production ran until 1996, During these years various models of the e34 were constructed. Initial models of the BMW e34 surprised the public as the vehicle was fitted with an abnormally small engine. This BMW’s engine was a mere 1.8L inline 4-cylinder with only 112hp. After shocking the public with the small engine, BMW designers made 6 more versions of the BMW e34, all with increasing engine size and displacement. One of the biggest shifts in BMW’s engine design of the e34 was the introduction of the V8 into a highly produced vehicle.  BMW was known for powering all of their cars with the reliable inline 6-cylinder engine, including V8 was quite new for BMW.  \nWith the new V8 engines in the designers repertoire, BMW created two models with the V8. The early V8 was a3.0L and the second was a more common 4.0 V8 with 282hp. This was a great relief to the public as the need for a faster car was needed to keep pace with the ever increasing speed of modern vehicles. \nBody styles were not quite present with the BMW e34, most of the model changes came in the form of the engine sizes and the transmission, being automatic or manual. However, the BMW e34 came in one unique body style which was their 5 door or station wagon model. After the success of the e30 station wagon, BMW designers were confident with the possible success of incorporating another station wagon into the BMW lineup. \n"
e341996.addEngine("V8",282, 4.0L);
carList.push(e341996);

const e361998 = new Car("E36",1998,"Black","Tan", "2 Door Coupe",24,"Manual",106.3 inches,
    "desc":"The BMW e36 was BMW third generation small compact sedan, the first to be produced after the notorious BMW e30. The chassis code for the car, known as the e30, refers to the model of the vehicle. Under this category various versions of the car were made using the e30 chassis code. The origination of this code comes from the German word for development, Entwicklung.  The car debuted in 1990 and production ran until 2000, During these years various models of the e36 were constructed. Engine displacements, transmission, and body styles were some of the features that were altered on the BMW e36. Initial models, following BMW’s tradition, began with a modest 1.6L inline 4-cylinder with 98 HP. With the car being pushed into the new age, the need for greater hp was ever present. Later models were fitted with BMW signature engine, the inline 6 cylinder. With the addition of the V8 into BMW’s lineup, the developers saved the V8 for their larger vehicles, the 3 series were still subjected to the inline 6. Later models of the BMW E36 were fitted with a 2.8L inline 6, pushing 190 hp. Diesel models were also offered for the BMW E36 but it very limited numbers. \nBody styles differ quite a lot with the BMW E36, similar to the E30 the simplicity of the E36 allowed for many style changes. The E36 was listed as a two-door coupe, and most productions models were of this car. Four door sedan modes were also created, but in limited numbers, adding to their desirability. In similar E30 fashion, the E36 came in a convertible design, as well as a five door or touring model. The last model included in the body style changes was the E36 compact. This style is one of the strangest BMW’s created as it is the first of its kind, breaking the mold of BMW style vehicles. \n"
e361998.addEngine("Inline 6",190, 2.8L);
carList.push(e361998);

const e382000 = new Car("E38",2000,"Grey","Black", "4 Door Sedan",30,"Automatic",115.4 inches,
    "desc":"The BMW e38 is BMW’s third generation luxury sedan. The chassis code for the car, known as the e38, refers to the model of the vehicle. Under this category various versions of the car were made using the e38 chassis code. The origination of this code comes from the German word for development, Entwicklung.  The car debuted in 1994 and production ran until 2001, During these years various models of the e38 were constructed. Engine displacements and transmissions were the only features altered for the e38 model. While there were only a few different models of the e32 created, the differences mainly rely under the hood. Initial models were fitted with the reliable 2.8L inline 6-cylinder engine with 190hp. Diesel models were also available upon release of the E38, these included 2.5L and 3.9L engines. Other than the diesel and inline 6 cylinder engines, later models were fitted with a 4.4L V8 and a 5.4L v12, with 282hp and 322hp respectively. \nSimilar to the E32, the BMW E38 did not come with many different styling models. Most if not all of the BMW E38’s are indistinguishable from other E38’s. The slightest body styling change came in 1998 with and updated facelift which changed the styling of the headlights. \n"
e382000.addEngine("V12",322, 5.4L);
carList.push(e382000);

const e392004 = new Car("E39",2004,"Red","Black", "4 Door Sedan",34,"Manual",111.4 inches,
    "desc":"The BMW e39 was BMW’s fourth generation full sized sedan model made by the company. The chassis code for the car, known as the e39, refers to the model of the vehicle. Under this category various versions of the car were made using the e39 chassis code. The origination of this code comes from the German word for development, Entwicklung.  The car debuted in 1995 and production ran until 2004, During these years various models of the e39 were constructed. Following the feedback from BMW’s previous full sized sedan, the E34, BMW’s initial models of the E39 were fitted with a much larger engine. The first models of the E39 were made with a 2.0L inline 6 cylinder engine with 148hp, a much better start to the lineup compared to the E34. With the E39 being a full sized sedan, BMW fitted these models with their version of the V8. The E39 was fitted with a 3.5L V8 with 241hp, the large V8 and a relatively small vehicle sized, proved to be a great setup as this vehicle was one of BMW’s most loved models. \nStyling changes remained little to none with the BMW 5 series. Similar to the BMW E34, the E39 came in only two body styles. The four door sedan model was one model, and the 5 door or station wagon version was also released. The BMW E39 resembles the E34 in a few ways, keep the body styling simple, and put great engines under the hood. \n"
e392004.addEngine("V8",241, 3.5L);
carList.push(e392004);
